<?php

namespace Customize\Repository;

use Customize\Entity\Agreement;
use Eccube\Repository\AbstractRepository;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * AgreementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgreementRepository extends AbstractRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, Agreement::class);
    }

    /**
     * @param int $id
     *
     * @return Agreement
     */
    public function get(int $id = 1)
    {
        $Agreement = $this->find($id);

        if (null === $Agreement) {
            $Agreement = new Agreement();
        }

        return $Agreement;
    }
}
