<?php

namespace Customize\Repository;

use Customize\Entity\BeerContainerCapacity;
use Eccube\Repository\AbstractRepository;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * BeerContainerCapacityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BeerContainerCapacityRepository extends AbstractRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, BeerContainerCapacity::class);
    }
}
