<?php

namespace Customize\Repository;

use Customize\Entity\Invoice;
use Eccube\Repository\AbstractRepository;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * InvoiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvoiceRepository extends AbstractRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, Invoice::class);
    }

    /**
     * @param int $id
     *
     * @return Invoice
     */
    public function get($id = 1)
    {
        $Invoice = $this->find($id);

        if (null === $Invoice) {
            throw new \Exception('Invoice not found. id = '.$id);
        }

        return $this->find($id);
    }
}
