monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            passthru_level: info
            handler: main_stream
        main_stream:
            type: stream
            path: "php://stderr"
            formatter: eccube.log.formatter.line
            level: debug
        front:
            type: fingers_crossed
            action_level: error
            passthru_level: info
            handler: front_stream
            channels: ['front', 'app', 'php']
        front_stream:
            type: stream
            path: "php://stderr"
            formatter: eccube.log.formatter.line
            level: debug
        admin:
            type: fingers_crossed
            action_level: error
            passthru_level: info
            handler: admin_stream
            channels: ['admin', 'app', 'php']
        admin_stream:
            type: stream
            path: "php://stderr"
            formatter: eccube.log.formatter.line
            level: debug
        console:
            type: console
            process_psr_3_messages: false
            channels: ['!event', '!doctrine']
